/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

/**
 *
 * @author mario
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        Hexagon1 = new javax.swing.JButton();
        Hexagon2 = new javax.swing.JButton();
        Hexagon3 = new javax.swing.JButton();
        Hexagon4 = new javax.swing.JButton();
        Hexagon5 = new javax.swing.JButton();
        Hexagon6 = new javax.swing.JButton();
        Hexagon7 = new javax.swing.JButton();
        Hexagon8 = new javax.swing.JButton();
        Hexagon9 = new javax.swing.JButton();
        Hexagon10 = new javax.swing.JButton();
        Hexagon11 = new javax.swing.JButton();
        Hexagon12 = new javax.swing.JButton();
        Hexagon13 = new javax.swing.JButton();
        Hexagon14 = new javax.swing.JButton();
        Hexagon15 = new javax.swing.JButton();
        Hexagon16 = new javax.swing.JButton();
        Hexagon17 = new javax.swing.JButton();
        Hexagon18 = new javax.swing.JButton();
        Hexagon19 = new javax.swing.JButton();
        Hexagon20 = new javax.swing.JButton();
        Hexagon21 = new javax.swing.JButton();
        Hexagon22 = new javax.swing.JButton();
        Hexagon23 = new javax.swing.JButton();
        Hexagon24 = new javax.swing.JButton();
        Hexagon25 = new javax.swing.JButton();
        Hexagon26 = new javax.swing.JButton();
        Hexagon27 = new javax.swing.JButton();
        Hexagon28 = new javax.swing.JButton();
        Hexagon29 = new javax.swing.JButton();
        Hexagon30 = new javax.swing.JButton();
        Hexagon31 = new javax.swing.JButton();
        Hexagon32 = new javax.swing.JButton();
        Hexagon33 = new javax.swing.JButton();
        Hexagon34 = new javax.swing.JButton();
        Hexagon35 = new javax.swing.JButton();
        Hexagon36 = new javax.swing.JButton();
        Hexagon37 = new javax.swing.JButton();
        Hexagon38 = new javax.swing.JButton();
        Hexagon39 = new javax.swing.JButton();
        Hexagon40 = new javax.swing.JButton();
        Hexagon41 = new javax.swing.JButton();
        Hexagon42 = new javax.swing.JButton();
        Hexagon43 = new javax.swing.JButton();
        Hexagon44 = new javax.swing.JButton();
        Hexagon45 = new javax.swing.JButton();
        Hexagon46 = new javax.swing.JButton();
        Hexagon47 = new javax.swing.JButton();
        Hexagon48 = new javax.swing.JButton();
        Hexagon49 = new javax.swing.JButton();
        Hexagon50 = new javax.swing.JButton();
        Hexagon51 = new javax.swing.JButton();
        Hexagon52 = new javax.swing.JButton();
        Hexagon53 = new javax.swing.JButton();
        Hexagon54 = new javax.swing.JButton();
        Hexagon55 = new javax.swing.JButton();
        Hexagon56 = new javax.swing.JButton();
        Hexagon57 = new javax.swing.JButton();
        Hexagon58 = new javax.swing.JButton();
        Hexagon59 = new javax.swing.JButton();
        Hexagon60 = new javax.swing.JButton();
        Hexagon61 = new javax.swing.JButton();
        Hexagon62 = new javax.swing.JButton();
        Hexagon63 = new javax.swing.JButton();
        Hexagon64 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        Hexagon1.setBackground(new java.awt.Color(255, 0, 51));
        Hexagon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TwitterHexagon.png"))); // NOI18N
        Hexagon1.setBorder(null);
        Hexagon1.setBorderPainted(false);
        Hexagon1.setContentAreaFilled(false);
        Hexagon1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TwitterHexagon.png"))); // NOI18N
        Hexagon2.setBorder(null);
        Hexagon2.setBorderPainted(false);
        Hexagon2.setContentAreaFilled(false);
        Hexagon2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TwitterHexagon.png"))); // NOI18N
        Hexagon3.setBorder(null);
        Hexagon3.setBorderPainted(false);
        Hexagon3.setContentAreaFilled(false);
        Hexagon3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TwitterHexagon.png"))); // NOI18N
        Hexagon4.setBorder(null);
        Hexagon4.setBorderPainted(false);
        Hexagon4.setContentAreaFilled(false);
        Hexagon4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TwitterHexagon.png"))); // NOI18N
        Hexagon5.setBorder(null);
        Hexagon5.setBorderPainted(false);
        Hexagon5.setContentAreaFilled(false);
        Hexagon5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TwitterHexagon.png"))); // NOI18N
        Hexagon6.setBorder(null);
        Hexagon6.setBorderPainted(false);
        Hexagon6.setContentAreaFilled(false);
        Hexagon6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TwitterHexagon.png"))); // NOI18N
        Hexagon7.setBorder(null);
        Hexagon7.setBorderPainted(false);
        Hexagon7.setContentAreaFilled(false);
        Hexagon7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TwitterHexagon.png"))); // NOI18N
        Hexagon8.setBorder(null);
        Hexagon8.setBorderPainted(false);
        Hexagon8.setContentAreaFilled(false);
        Hexagon8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TwitterHexagon.png"))); // NOI18N
        Hexagon9.setBorder(null);
        Hexagon9.setBorderPainted(false);
        Hexagon9.setContentAreaFilled(false);
        Hexagon9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TwitterHexagon.png"))); // NOI18N
        Hexagon10.setBorder(null);
        Hexagon10.setBorderPainted(false);
        Hexagon10.setContentAreaFilled(false);
        Hexagon10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EmptyHexagon.png"))); // NOI18N
        Hexagon11.setBorder(null);
        Hexagon11.setBorderPainted(false);
        Hexagon11.setContentAreaFilled(false);
        Hexagon11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EmptyHexagon.png"))); // NOI18N
        Hexagon12.setBorder(null);
        Hexagon12.setBorderPainted(false);
        Hexagon12.setContentAreaFilled(false);
        Hexagon12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EmptyHexagon.png"))); // NOI18N
        Hexagon13.setBorder(null);
        Hexagon13.setBorderPainted(false);
        Hexagon13.setContentAreaFilled(false);
        Hexagon13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EmptyHexagon.png"))); // NOI18N
        Hexagon14.setBorder(null);
        Hexagon14.setBorderPainted(false);
        Hexagon14.setContentAreaFilled(false);
        Hexagon14.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EmptyHexagon.png"))); // NOI18N
        Hexagon15.setBorder(null);
        Hexagon15.setBorderPainted(false);
        Hexagon15.setContentAreaFilled(false);
        Hexagon15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EmptyHexagon.png"))); // NOI18N
        Hexagon16.setBorder(null);
        Hexagon16.setBorderPainted(false);
        Hexagon16.setContentAreaFilled(false);
        Hexagon16.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EmptyHexagon.png"))); // NOI18N
        Hexagon17.setBorder(null);
        Hexagon17.setBorderPainted(false);
        Hexagon17.setContentAreaFilled(false);
        Hexagon17.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EmptyHexagon.png"))); // NOI18N
        Hexagon18.setBorder(null);
        Hexagon18.setBorderPainted(false);
        Hexagon18.setContentAreaFilled(false);
        Hexagon18.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EmptyHexagon.png"))); // NOI18N
        Hexagon19.setBorder(null);
        Hexagon19.setBorderPainted(false);
        Hexagon19.setContentAreaFilled(false);
        Hexagon19.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EmptyHexagon.png"))); // NOI18N
        Hexagon20.setBorder(null);
        Hexagon20.setBorderPainted(false);
        Hexagon20.setContentAreaFilled(false);
        Hexagon20.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EmptyHexagon.png"))); // NOI18N
        Hexagon21.setBorder(null);
        Hexagon21.setBorderPainted(false);
        Hexagon21.setContentAreaFilled(false);
        Hexagon21.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EmptyHexagon.png"))); // NOI18N
        Hexagon22.setBorder(null);
        Hexagon22.setBorderPainted(false);
        Hexagon22.setContentAreaFilled(false);
        Hexagon22.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EmptyHexagon.png"))); // NOI18N
        Hexagon23.setBorder(null);
        Hexagon23.setBorderPainted(false);
        Hexagon23.setContentAreaFilled(false);
        Hexagon23.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EmptyHexagon.png"))); // NOI18N
        Hexagon24.setBorder(null);
        Hexagon24.setBorderPainted(false);
        Hexagon24.setContentAreaFilled(false);
        Hexagon24.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EmptyHexagon.png"))); // NOI18N
        Hexagon25.setBorder(null);
        Hexagon25.setBorderPainted(false);
        Hexagon25.setContentAreaFilled(false);
        Hexagon25.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EmptyHexagon.png"))); // NOI18N
        Hexagon26.setBorder(null);
        Hexagon26.setBorderPainted(false);
        Hexagon26.setContentAreaFilled(false);
        Hexagon26.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EmptyHexagon.png"))); // NOI18N
        Hexagon27.setBorder(null);
        Hexagon27.setBorderPainted(false);
        Hexagon27.setContentAreaFilled(false);
        Hexagon27.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EmptyHexagon.png"))); // NOI18N
        Hexagon28.setBorder(null);
        Hexagon28.setBorderPainted(false);
        Hexagon28.setContentAreaFilled(false);
        Hexagon28.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EmptyHexagon.png"))); // NOI18N
        Hexagon29.setBorder(null);
        Hexagon29.setBorderPainted(false);
        Hexagon29.setContentAreaFilled(false);
        Hexagon29.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EmptyHexagon.png"))); // NOI18N
        Hexagon30.setBorder(null);
        Hexagon30.setBorderPainted(false);
        Hexagon30.setContentAreaFilled(false);
        Hexagon30.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EmptyHexagon.png"))); // NOI18N
        Hexagon31.setBorder(null);
        Hexagon31.setBorderPainted(false);
        Hexagon31.setContentAreaFilled(false);
        Hexagon31.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EmptyHexagon.png"))); // NOI18N
        Hexagon32.setBorder(null);
        Hexagon32.setBorderPainted(false);
        Hexagon32.setContentAreaFilled(false);
        Hexagon32.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EmptyHexagon.png"))); // NOI18N
        Hexagon33.setBorder(null);
        Hexagon33.setBorderPainted(false);
        Hexagon33.setContentAreaFilled(false);
        Hexagon33.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EmptyHexagon.png"))); // NOI18N
        Hexagon34.setBorder(null);
        Hexagon34.setBorderPainted(false);
        Hexagon34.setContentAreaFilled(false);
        Hexagon34.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EmptyHexagon.png"))); // NOI18N
        Hexagon35.setBorder(null);
        Hexagon35.setBorderPainted(false);
        Hexagon35.setContentAreaFilled(false);
        Hexagon35.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EmptyHexagon.png"))); // NOI18N
        Hexagon36.setBorder(null);
        Hexagon36.setBorderPainted(false);
        Hexagon36.setContentAreaFilled(false);
        Hexagon36.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EmptyHexagon.png"))); // NOI18N
        Hexagon37.setBorder(null);
        Hexagon37.setBorderPainted(false);
        Hexagon37.setContentAreaFilled(false);
        Hexagon37.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EmptyHexagon.png"))); // NOI18N
        Hexagon38.setBorder(null);
        Hexagon38.setBorderPainted(false);
        Hexagon38.setContentAreaFilled(false);
        Hexagon38.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EmptyHexagon.png"))); // NOI18N
        Hexagon39.setBorder(null);
        Hexagon39.setBorderPainted(false);
        Hexagon39.setContentAreaFilled(false);
        Hexagon39.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EmptyHexagon.png"))); // NOI18N
        Hexagon40.setBorder(null);
        Hexagon40.setBorderPainted(false);
        Hexagon40.setContentAreaFilled(false);
        Hexagon40.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EmptyHexagon.png"))); // NOI18N
        Hexagon41.setBorder(null);
        Hexagon41.setBorderPainted(false);
        Hexagon41.setContentAreaFilled(false);
        Hexagon41.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EmptyHexagon.png"))); // NOI18N
        Hexagon42.setBorder(null);
        Hexagon42.setBorderPainted(false);
        Hexagon42.setContentAreaFilled(false);
        Hexagon42.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EmptyHexagon.png"))); // NOI18N
        Hexagon43.setBorder(null);
        Hexagon43.setBorderPainted(false);
        Hexagon43.setContentAreaFilled(false);
        Hexagon43.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EmptyHexagon.png"))); // NOI18N
        Hexagon44.setBorder(null);
        Hexagon44.setBorderPainted(false);
        Hexagon44.setContentAreaFilled(false);
        Hexagon44.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EmptyHexagon.png"))); // NOI18N
        Hexagon45.setBorder(null);
        Hexagon45.setBorderPainted(false);
        Hexagon45.setContentAreaFilled(false);
        Hexagon45.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EmptyHexagon.png"))); // NOI18N
        Hexagon46.setBorder(null);
        Hexagon46.setBorderPainted(false);
        Hexagon46.setContentAreaFilled(false);
        Hexagon46.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EmptyHexagon.png"))); // NOI18N
        Hexagon47.setBorder(null);
        Hexagon47.setBorderPainted(false);
        Hexagon47.setContentAreaFilled(false);
        Hexagon47.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EmptyHexagon.png"))); // NOI18N
        Hexagon48.setBorder(null);
        Hexagon48.setBorderPainted(false);
        Hexagon48.setContentAreaFilled(false);
        Hexagon48.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EmptyHexagon.png"))); // NOI18N
        Hexagon49.setBorder(null);
        Hexagon49.setBorderPainted(false);
        Hexagon49.setContentAreaFilled(false);
        Hexagon49.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EmptyHexagon.png"))); // NOI18N
        Hexagon50.setBorder(null);
        Hexagon50.setBorderPainted(false);
        Hexagon50.setContentAreaFilled(false);
        Hexagon50.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EmptyHexagon.png"))); // NOI18N
        Hexagon51.setBorder(null);
        Hexagon51.setBorderPainted(false);
        Hexagon51.setContentAreaFilled(false);
        Hexagon51.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EmptyHexagon.png"))); // NOI18N
        Hexagon52.setBorder(null);
        Hexagon52.setBorderPainted(false);
        Hexagon52.setContentAreaFilled(false);
        Hexagon52.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EmptyHexagon.png"))); // NOI18N
        Hexagon53.setBorder(null);
        Hexagon53.setBorderPainted(false);
        Hexagon53.setContentAreaFilled(false);
        Hexagon53.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EmptyHexagon.png"))); // NOI18N
        Hexagon54.setBorder(null);
        Hexagon54.setBorderPainted(false);
        Hexagon54.setContentAreaFilled(false);
        Hexagon54.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/YoutubeHexagon.png"))); // NOI18N
        Hexagon55.setBorder(null);
        Hexagon55.setBorderPainted(false);
        Hexagon55.setContentAreaFilled(false);
        Hexagon55.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/YoutubeHexagon.png"))); // NOI18N
        Hexagon56.setBorder(null);
        Hexagon56.setBorderPainted(false);
        Hexagon56.setContentAreaFilled(false);
        Hexagon56.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/YoutubeHexagon.png"))); // NOI18N
        Hexagon57.setBorder(null);
        Hexagon57.setBorderPainted(false);
        Hexagon57.setContentAreaFilled(false);
        Hexagon57.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/YoutubeHexagon.png"))); // NOI18N
        Hexagon58.setBorder(null);
        Hexagon58.setBorderPainted(false);
        Hexagon58.setContentAreaFilled(false);
        Hexagon58.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/YoutubeHexagon.png"))); // NOI18N
        Hexagon59.setBorder(null);
        Hexagon59.setBorderPainted(false);
        Hexagon59.setContentAreaFilled(false);
        Hexagon59.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/YoutubeHexagon.png"))); // NOI18N
        Hexagon60.setBorder(null);
        Hexagon60.setBorderPainted(false);
        Hexagon60.setContentAreaFilled(false);
        Hexagon60.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/YoutubeHexagon.png"))); // NOI18N
        Hexagon61.setBorder(null);
        Hexagon61.setBorderPainted(false);
        Hexagon61.setContentAreaFilled(false);
        Hexagon61.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/YoutubeHexagon.png"))); // NOI18N
        Hexagon62.setBorder(null);
        Hexagon62.setBorderPainted(false);
        Hexagon62.setContentAreaFilled(false);
        Hexagon62.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/YoutubeHexagon.png"))); // NOI18N
        Hexagon63.setBorder(null);
        Hexagon63.setBorderPainted(false);
        Hexagon63.setContentAreaFilled(false);
        Hexagon63.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hexagon64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/YoutubeHexagon.png"))); // NOI18N
        Hexagon64.setBorder(null);
        Hexagon64.setBorderPainted(false);
        Hexagon64.setContentAreaFilled(false);
        Hexagon64.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(Hexagon8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Hexagon6)
                    .addComponent(Hexagon7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Hexagon1)
                            .addComponent(Hexagon2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                                .addComponent(Hexagon10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Hexagon11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Hexagon21)
                                    .addComponent(Hexagon20))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Hexagon22)
                                    .addComponent(Hexagon23, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Hexagon35)
                                    .addComponent(Hexagon36)))
                            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                                        .addComponent(Hexagon4)
                                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(Hexagon14))
                                            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Hexagon13))))
                                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                                        .addComponent(Hexagon3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Hexagon12))
                                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(Hexagon15)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                                        .addComponent(Hexagon19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Hexagon24)
                                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Hexagon33))
                                            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(Hexagon34))))
                                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                                                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(Hexagon17)
                                                    .addComponent(Hexagon16))
                                                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(Hexagon28))
                                                        .addGroup(PanelPrincipalLayout.createSequentialGroup()
                                                            .addGap(6, 6, 6)
                                                            .addComponent(Hexagon27)))
                                                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(Hexagon26))))
                                            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                                                .addComponent(Hexagon18)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Hexagon25)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Hexagon29)
                                            .addComponent(Hexagon30)
                                            .addComponent(Hexagon31)
                                            .addComponent(Hexagon32)))))))
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addComponent(Hexagon5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Hexagon9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Hexagon42)
                    .addComponent(Hexagon43)
                    .addComponent(Hexagon41)
                    .addComponent(Hexagon40)
                    .addComponent(Hexagon39)
                    .addComponent(Hexagon38)
                    .addComponent(Hexagon37))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Hexagon47)
                            .addComponent(Hexagon46)
                            .addComponent(Hexagon45)
                            .addComponent(Hexagon44))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Hexagon54)
                            .addComponent(Hexagon53)
                            .addComponent(Hexagon52)
                            .addComponent(Hexagon51)))
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Hexagon49)
                            .addComponent(Hexagon48))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Hexagon50)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Hexagon58)
                    .addComponent(Hexagon57)
                    .addComponent(Hexagon56)
                    .addComponent(Hexagon55))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Hexagon61)
                    .addComponent(Hexagon60)
                    .addComponent(Hexagon59))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Hexagon63)
                    .addComponent(Hexagon62))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Hexagon64)
                .addContainerGap(635, Short.MAX_VALUE))
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(Hexagon10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                                .addComponent(Hexagon3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Hexagon4))
                            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                                .addComponent(Hexagon7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Hexagon6))))
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(Hexagon8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Hexagon9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Hexagon21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addComponent(Hexagon2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Hexagon1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Hexagon5)
                        .addGap(227, 227, 227))
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addComponent(Hexagon20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Hexagon19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Hexagon18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Hexagon17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Hexagon16)
                        .addGap(175, 175, 175))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                .addGap(0, 94, Short.MAX_VALUE)
                .addComponent(Hexagon36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Hexagon35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Hexagon34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Hexagon33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Hexagon32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Hexagon31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Hexagon30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Hexagon29)
                .addGap(136, 136, 136))
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelPrincipalLayout.createSequentialGroup()
                            .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(PanelPrincipalLayout.createSequentialGroup()
                                    .addGap(154, 154, 154)
                                    .addComponent(Hexagon11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Hexagon12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Hexagon13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Hexagon14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Hexagon15))
                                .addGroup(PanelPrincipalLayout.createSequentialGroup()
                                    .addGap(114, 114, 114)
                                    .addComponent(Hexagon22)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Hexagon23)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Hexagon24)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Hexagon25)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Hexagon26)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Hexagon27)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Hexagon28))
                        .addGroup(PanelPrincipalLayout.createSequentialGroup()
                            .addGap(112, 112, 112)
                            .addComponent(Hexagon37)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Hexagon38)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Hexagon39)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Hexagon40)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Hexagon41)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Hexagon42)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Hexagon43))
                        .addGroup(PanelPrincipalLayout.createSequentialGroup()
                            .addGap(153, 153, 153)
                            .addComponent(Hexagon50)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Hexagon51)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Hexagon52)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Hexagon53)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Hexagon54))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                            .addGap(136, 136, 136)
                            .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                                    .addComponent(Hexagon49)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Hexagon48)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Hexagon47)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Hexagon46)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Hexagon45)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Hexagon44)
                                    .addGap(18, 18, 18))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                                    .addComponent(Hexagon58)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Hexagon57)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Hexagon56)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Hexagon55)
                                    .addGap(51, 51, 51))
                                .addGroup(PanelPrincipalLayout.createSequentialGroup()
                                    .addGap(55, 55, 55)
                                    .addComponent(Hexagon59)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Hexagon60)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Hexagon61))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                                    .addComponent(Hexagon63)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Hexagon62)
                                    .addGap(87, 87, 87)))))
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(Hexagon64)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Hexagon1;
    public javax.swing.JButton Hexagon10;
    public javax.swing.JButton Hexagon11;
    public javax.swing.JButton Hexagon12;
    public javax.swing.JButton Hexagon13;
    public javax.swing.JButton Hexagon14;
    public javax.swing.JButton Hexagon15;
    public javax.swing.JButton Hexagon16;
    public javax.swing.JButton Hexagon17;
    public javax.swing.JButton Hexagon18;
    public javax.swing.JButton Hexagon19;
    public javax.swing.JButton Hexagon2;
    public javax.swing.JButton Hexagon20;
    public javax.swing.JButton Hexagon21;
    public javax.swing.JButton Hexagon22;
    public javax.swing.JButton Hexagon23;
    public javax.swing.JButton Hexagon24;
    public javax.swing.JButton Hexagon25;
    public javax.swing.JButton Hexagon26;
    public javax.swing.JButton Hexagon27;
    public javax.swing.JButton Hexagon28;
    public javax.swing.JButton Hexagon29;
    public javax.swing.JButton Hexagon3;
    public javax.swing.JButton Hexagon30;
    public javax.swing.JButton Hexagon31;
    public javax.swing.JButton Hexagon32;
    public javax.swing.JButton Hexagon33;
    public javax.swing.JButton Hexagon34;
    public javax.swing.JButton Hexagon35;
    public javax.swing.JButton Hexagon36;
    public javax.swing.JButton Hexagon37;
    public javax.swing.JButton Hexagon38;
    public javax.swing.JButton Hexagon39;
    public javax.swing.JButton Hexagon4;
    public javax.swing.JButton Hexagon40;
    public javax.swing.JButton Hexagon41;
    public javax.swing.JButton Hexagon42;
    public javax.swing.JButton Hexagon43;
    public javax.swing.JButton Hexagon44;
    public javax.swing.JButton Hexagon45;
    public javax.swing.JButton Hexagon46;
    public javax.swing.JButton Hexagon47;
    public javax.swing.JButton Hexagon48;
    public javax.swing.JButton Hexagon49;
    public javax.swing.JButton Hexagon5;
    public javax.swing.JButton Hexagon50;
    public javax.swing.JButton Hexagon51;
    public javax.swing.JButton Hexagon52;
    public javax.swing.JButton Hexagon53;
    public javax.swing.JButton Hexagon54;
    public javax.swing.JButton Hexagon55;
    public javax.swing.JButton Hexagon56;
    public javax.swing.JButton Hexagon57;
    public javax.swing.JButton Hexagon58;
    public javax.swing.JButton Hexagon59;
    public javax.swing.JButton Hexagon6;
    public javax.swing.JButton Hexagon60;
    public javax.swing.JButton Hexagon61;
    public javax.swing.JButton Hexagon62;
    public javax.swing.JButton Hexagon63;
    public javax.swing.JButton Hexagon64;
    public javax.swing.JButton Hexagon7;
    public javax.swing.JButton Hexagon8;
    public javax.swing.JButton Hexagon9;
    private javax.swing.JPanel PanelPrincipal;
    // End of variables declaration//GEN-END:variables
}
